import { SceneDescription, StickerDescription, StickerPackDescription } from './pl-scenes-factory.service';

const potatoBodySticker: StickerDescription = {
    name: 'potato-body',
    width: 27.6,
    height: 40,
    baseLayer: true,
    displayName: '',
};

const eyeStickers: StickerDescription[] = [
    {
        name: 'eyes',
        width: 15.5,
        height: 8.4,
        baseLayer: null,
        displayName: 'Eyes',
    },
    {
        name: 'eyes-with-lashes',
        width: 17.4,
        height: 9.1,
        baseLayer: null,
        displayName: 'Eyes with Lashes',
    },
    {
        name: 'drowsy-eyes',
        width: 15.9,
        height: 8.4,
        baseLayer: null,
        displayName: 'Drowsy Eyes',
    },
    {
        name: 'smaller-eyes-with-lashes',
        width: 21.3,
        height: 7.7,
        baseLayer: null,
        displayName: 'Smaller Eyes with Lashes',
    },
    {
        name: 'yellow-glasses',
        width: 27,
        height: 10.5,
        baseLayer: null,
        displayName: 'Yellow Glasses',
    },
    {
        name: 'eye-patch',
        width: 21,
        height: 10.5,
        baseLayer: null,
        displayName: 'Eye Patch',
    },
    {
        name: 'blue-sunglasses',
        width: 24.4,
        height: 10,
        baseLayer: null,
        displayName: 'Blue Sunglasses',
    },
    {
        name: 'pink-eye-mask',
        width: 23.4,
        height: 13,
        baseLayer: null,
        displayName: 'Pink Eye Mask',
    },
    {
        name: 'purple-glasses',
        width: 26,
        height: 10,
        baseLayer: null,
        displayName: 'Purple Glasses',
    },
];

const noseStickers: StickerDescription[] = [
    {
        name: 'pink-nose',
        width: 14,
        height: 9.8,
        baseLayer: null,
        displayName: 'Pink Nose',
    },
    {
        name: 'red-nose',
        width: 14,
        height: 9.8,
        baseLayer: null,
        displayName: 'Red Nose',
    },
];

const mouthStickers: StickerDescription[] = [
    {
        name: 'buck-teeth',
        width: 16,
        height: 9.7,
        baseLayer: null,
        displayName: 'Buck Teeth',
    },
    {
        name: 'tongue',
        width: 14,
        height: 9,
        baseLayer: null,
        displayName: 'Tongue',
    },
    {
        name: 'teeth',
        width: 18,
        height: 11.1,
        baseLayer: null,
        displayName: 'Teeth',
    },
    {
        name: 'tongue-out',
        width: 13.4,
        height: 12.6,
        baseLayer: null,
        displayName: 'Tongue Out',
    },
    {
        name: 'open-mouth',
        width: 7.7,
        height: 11.5,
        baseLayer: null,
        displayName: 'Open Mouth',
    },
    {
        name: 'smile',
        width: 15.4,
        height: 11.5,
        baseLayer: null,
        displayName: 'Smile',
    },
    {
        name: 'pacifier',
        width: 16,
        height: 12.5,
        baseLayer: null,
        displayName: 'Pacifier',
    },
    {
        name: 'red-lips',
        width: 16.5,
        height: 10.2,
        baseLayer: null,
        displayName: 'Red Lips',
    },
];

const earStickers: StickerDescription[] = [
    {
        name: 'left-ear-with-earring',
        width: 8.4,
        height: 15.9,
        baseLayer: null,
        displayName: 'Left Ear with Earring',
    },
    {
        name: 'right-ear-with-earring',
        width: 8.4,
        height: 15.9,
        baseLayer: null,
        displayName: 'Right Ear with Earring',
    },
    {
        name: 'left-ear-with-lobe',
        width: 8.3,
        height: 12.2,
        baseLayer: null,
        displayName: 'Left Ear with Lobe',
    },
    {
        name: 'right-ear-with-lobe',
        width: 8.3,
        height: 12.2,
        baseLayer: null,
        displayName: 'Right Ear with Lobe',
    },
    {
        name: 'left-ear-broad-lobe',
        width: 8.4,
        height: 9,
        baseLayer: null,
        displayName: 'Left Ear Broad Lobe',
    },
    {
        name: 'right-ear-broad-lobe',
        width: 8.4,
        height: 9,
        baseLayer: null,
        displayName: 'Right Ear Broad Lobe',
    },
    {
        name: 'round-left-ear',
        width: 8.5,
        height: 10.9,
        baseLayer: null,
        displayName: 'Round Left Ear',
    },
    {
        name: 'round-right-ear',
        width: 8.5,
        height: 10.9,
        baseLayer: null,
        displayName: 'Round Right Ear',
    },
];

const armStickers: StickerDescription[] = [
    {
        name: 'left-side-thumbs-up',
        width: 23.3,
        height: 19.1,
        baseLayer: null,
        displayName: 'Left Side Thumbs Up',
    },
    {
        name: 'right-side-thumbs-up',
        width: 23.3,
        height: 19.1,
        baseLayer: null,
        displayName: 'Right Side Thumbs Up',
    },
    {
        name: 'left-side-peace-sign',
        width: 18.4,
        height: 21,
        baseLayer: null,
        displayName: 'Left Side Peace Sign',
    },
    {
        name: 'right-side-peace-sign',
        width: 18.4,
        height: 21,
        baseLayer: null,
        displayName: 'Right Side Peace Sign',
    },
    {
        name: 'left-side-flex',
        width: 13.8,
        height: 19.1,
        baseLayer: null,
        displayName: 'Left Side Flex',
    },
    {
        name: 'right-side-flex',
        width: 13.8,
        height: 19.1,
        baseLayer: null,
        displayName: 'Right Side Flex',
    },
    {
        name: 'left-side-on-hip',
        width: 16.3,
        height: 18.7,
        baseLayer: null,
        displayName: 'Left Side on Hip',
    },
    {
        name: 'right-side-on-hip',
        width: 16.3,
        height: 18.7,
        baseLayer: null,
        displayName: 'Right Side on Hip',
    },
    {
        name: 'left-side-behind-back',
        width: 18.6,
        height: 16,
        baseLayer: null,
        displayName: 'Left Side Behind Back',
    },
    {
        name: 'right-side-behind-back',
        width: 18.6,
        height: 16,
        baseLayer: null,
        displayName: 'Right Side Behind Back',
    },
    {
        name: 'left-side-horn-sign',
        width: 17.7,
        height: 24.8,
        baseLayer: null,
        displayName: 'Left Side Horn Sign',
    },
    {
        name: 'right-side-horn-sign',
        width: 17.7,
        height: 24.8,
        baseLayer: null,
        displayName: 'Right Side Horn Sign',
    },
    {
        name: 'left-side-wave',
        width: 14,
        height: 31.8,
        baseLayer: null,
        displayName: 'Left Side Wave',
    },
    {
        name: 'right-side-wave',
        width: 14,
        height: 31.8,
        baseLayer: null,
        displayName: 'Right Side Wave',
    },
    {
        name: 'left-side-down',
        width: 16.2,
        height: 26.6,
        baseLayer: null,
        displayName: 'Left Side Down',
    },
    {
        name: 'right-side-down',
        width: 16.2,
        height: 26.6,
        baseLayer: null,
        displayName: 'Right Side Down',
    },
    {
        name: 'left-side-point',
        width: 24.4,
        height: 22.7,
        baseLayer: null,
        displayName: 'Left Side Point',
    },
    {
        name: 'right-side-point',
        width: 24.4,
        height: 22.7,
        baseLayer: null,
        displayName: 'Right Side Point',
    },
];

const headwareStickers: StickerDescription[] = [
    {
        name: 'red-bandana',
        width: 27,
        height: 9.7,
        baseLayer: null,
        displayName: 'Red Bandana',
    },
    {
        name: 'green-clown-hat',
        width: 23.9,
        height: 26.5,
        baseLayer: null,
        displayName: 'Green Clown Hat',
    },
    {
        name: 'fireman-hat',
        width: 25,
        height: 16.9,
        baseLayer: null,
        displayName: 'Firefighter Hat',
    },
    {
        name: 'pirate-hat',
        width: 32,
        height: 18.5,
        baseLayer: null,
        displayName: 'Pirate Hat',
    },
    {
        name: 'pink-hat-with-bow',
        width: 24.8,
        height: 14,
        baseLayer: null,
        displayName: 'Pink Hat with Bow',
    },
    {
        name: 'police-hat',
        width: 24.5,
        height: 13.7,
        baseLayer: null,
        displayName: 'Police Hat',
    },
    {
        name: 'green-baseball-cap',
        width: 24,
        height: 11.7,
        baseLayer: null,
        displayName: 'Green Baseball Hat',
    },
    {
        name: 'green-beanie',
        width: 24,
        height: 17.1,
        baseLayer: null,
        displayName: 'Green Beanie',
    },
    {
        name: 'red-spinner-hat',
        width: 22.5,
        height: 11.5,
        baseLayer: null,
        displayName: 'Red Spinner Hat',
    },
    {
        name: 'red-baseball-cap',
        width: 19,
        height: 11.1,
        baseLayer: null,
        displayName: 'Red Baseball Cap',
    },
    {
        name: 'brown-bowler-hat',
        width: 24.6,
        height: 13.8,
        baseLayer: null,
        displayName: 'Brown Bowler Hat',
    },
    {
        name: 'pink-hat-and-ponytail',
        width: 29,
        height: 10.6,
        baseLayer: null,
        displayName: 'Pink Hat and Ponytail',
    },
];

const feetStickers: StickerDescription[] = [
    {
        name: 'orange-feet',
        width: 33,
        height: 13.3,
        baseLayer: null,
        displayName: 'Orange Feet',
    },
    {
        name: 'green-shoes',
        width: 34,
        height: 13.4,
        baseLayer: null,
        displayName: 'Green Shoes',
    },
    {
        name: 'green-heels',
        width: 28.9,
        height: 15,
        baseLayer: null,
        displayName: 'Green Heels',
    },
    {
        name: 'brown-boots',
        width: 31.3,
        height: 13,
        baseLayer: null,
        displayName: 'Brown Boots',
    },
    {
        name: 'blue-shoes',
        width: 29,
        height: 15.5,
        baseLayer: null,
        displayName: 'Blue Shoes',
    },
    {
        name: 'purple-skiing-shoes',
        width: 30,
        height: 24,
        baseLayer: null,
        displayName: 'Purple Skiing Shoes',
    },
    {
        name: 'pirate-stump',
        width: 27.3,
        height: 15,
        baseLayer: null,
        displayName: 'Pirate Stump',
    },
    {
        name: 'yellow-boots',
        width: 31.5,
        height: 16,
        baseLayer: null,
        displayName: 'Yellow Shoes',
    },
    {
        name: 'pink-slippers',
        width: 33,
        height: 15.6,
        baseLayer: null,
        displayName: 'Pink Slippers',
    },
    {
        name: 'red-heels',
        width: 28,
        height: 15.2,
        baseLayer: null,
        displayName: 'Red Heels',
    },
];

const mustacheStickers: StickerDescription[] = [
    {
        name: 'bushy',
        width: 24.2,
        height: 9,
        baseLayer: null,
        displayName: 'Bushy',
    },
    {
        name: 'spreadout',
        width: 24.9,
        height: 7.5,
        baseLayer: null,
        displayName: 'Spreadout',
    },
    {
        name: 'upbraid',
        width: 21.3,
        height: 9.7,
        baseLayer: null,
        displayName: 'Upbraid',
    },
    {
        name: 'downbraid',
        width: 20.6,
        height: 7.5,
        baseLayer: null,
        displayName: 'Downbraid',
    },
    {
        name: 'combed',
        width: 21.7,
        height: 11.4,
        baseLayer: null,
        displayName: 'Combed',
    },
    {
        name: 'handlebar',
        width: 26,
        height: 7.8,
        baseLayer: null,
        displayName: 'Handlebar',
    },
    {
        name: 'classic',
        width: 21.9,
        height: 10.3,
        baseLayer: null,
        displayName: 'Classic',
    },
];

export const potatoHeadStickerPacks: StickerPackDescription[] = [
    {
        name: 'potatohead-eyes',
        displayName: 'Eyes and Accessories',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...eyeStickers],
    },
    {
        name: 'potatohead-noses',
        displayName: 'Noses',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...noseStickers],
    },
    {
        name: 'potatohead-mouths',
        displayName: 'Mouths',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...mouthStickers],
    },
    {
        name: 'potatohead-ears',
        displayName: 'Ears and Ear Accessories',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...earStickers],
    },
    {
        name: 'potatohead-arms',
        displayName: 'Arms and Hands',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...armStickers],
    },
    {
        name: 'potatohead-headwear',
        displayName: 'Headware',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...headwareStickers],
    },
    {
        name: 'potatohead-mustaches',
        displayName: 'Mustaches',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...mustacheStickers],
    },
    {
        name: 'potatohead-feet',
        displayName: 'Feet and Footwear',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...feetStickers],
    },
    {
        name: 'potatohead-all',
        displayName: 'All',
        location: 'potatohead',
        stickers: [potatoBodySticker, ...eyeStickers, ...noseStickers, ...mouthStickers,
            ...earStickers, ...armStickers, ...headwareStickers, ...mustacheStickers, ...feetStickers],
    },
];

export const potatoHeadScenes: SceneDescription[] = [
    {
        displayName: 'Mountain Climbing',
        name: 'mountain-climbing',
        location: 'potatohead',
        background: 'mountain-climbing',
        backgroundImageSuffix: 'jpg',
    },
    {
        displayName: 'In the Sky',
        name: 'in-the-sky',
        location: 'potatohead',
        background: 'in-the-sky',
        backgroundImageSuffix: 'jpg',
    },
    {
        displayName: 'Space',
        name: 'space',
        location: 'potatohead',
        background: 'space',
    },
    {
        displayName: 'Ice',
        name: 'ice',
        location: 'potatohead',
        background: 'ice',
    },
    {
        displayName: 'Farm',
        name: 'farm',
        location: 'potatohead',
        background: 'farm',
    },
    {
        displayName: 'Bedroom',
        name: 'bedroom',
        location: 'potatohead',
        background: 'bedroom',
    },
    {
        displayName: 'Underwater',
        name: 'underwater',
        location: 'potatohead',
        background: 'underwater',
        backgroundImageSuffix: 'jpg',
    },
    {
        displayName: 'Palms',
        name: 'palms',
        location: 'potatohead',
        background: 'palms',
        backgroundImageSuffix: 'jpg',
    },
    {
        displayName: 'Haunted House',
        name: 'haunted-house',
        location: 'potatohead',
        background: 'haunted-house',
        backgroundImageSuffix: 'jpg',
    },
];
